[supabase]
url = "https://flrvzxeypjzbfbftyrit.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4cnZ6eGV5cGpzYmZiZnR5cml0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjUwODg2NDYsImV4cCI6MjA0MDY2NDY0Nn0.B1WvLKuKqvRG8SYUOcg6R4u_XSlTzV9p7a8nV0oPp3g"
