[supabase]
url = https://phishing awareness app.supabase.co
anon_key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZscnZ6eGV5cGp6YmZiZnR5cml0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0ODcyNDMsImV4cCI6MjA3NzA2MzI0M30.kY-cK8eDKSpONzy11cMqSGmLj13XeBGycdmYfcp8eUg
